//! One interface over the available sources.
//!
//! [ADR-0008] specifies four sources in priority order, degrading rather than
//! failing, and **always reporting which one is live**. That last part is the
//! design: silently answering from a stale export while looking like a live
//! library is a correctness problem in a citation tool, not a graceful
//! fallback, so [`Library::source`] is not optional detail.
//!
//! # What is implemented
//!
//! | Tier | Source | State |
//! |---|---|---|
//! | 1 | Better BibTeX JSON-RPC | not yet — see below |
//! | 2 | Zotero 7 local API | implemented, unverified against a live Zotero |
//! | 3 | Watched exported `.bib` | not yet |
//! | 4 | `zotero.sqlite` copy | implemented and verified against a real library |
//!
//! Better BibTeX is the tier that matters most for correctness, because it owns
//! the citation key that a co-author's `.bib` already contains. Until it is
//! implemented, keys for items without one are generated by
//! [`crate::bib::generate_key`], and [`Library::keys_are_authoritative`] reports
//! `false` so the interface can say so rather than let a user discover the
//! mismatch in a co-author's document.
//!
//! [ADR-0008]: https://github.com/GeneralPawz/yaz/blob/main/docs/adr/0008-zotero-integration.md

use camino::Utf8PathBuf;
use std::sync::Mutex;

use crate::ActiveSource;
use crate::datadir::{self, DataDir};
use crate::error::{Error, Result};
use crate::local_api::LocalApi;
use crate::model::{Annotation, Item};
use crate::sqlite::SqliteSource;

/// How to find the library.
#[derive(Debug, Clone, Default)]
pub struct Config {
    /// An explicit data directory, overriding discovery.
    pub data_dir: Option<Utf8PathBuf>,
    /// Directory for the read-only database copy.
    pub scratch: Utf8PathBuf,
}

/// A connected Zotero library.
pub struct Library {
    source: ActiveSource,
    live: Option<LocalApi>,
    /// `Mutex` because `rusqlite::Connection` is `Send` but not `Sync`, and this
    /// is held in shared application state. The lock is never held across an
    /// `await`; every sqlite call completes synchronously inside its own scope.
    offline: Option<Mutex<SqliteSource>>,
    /// Where the offline library was found, for the interface to explain.
    pub data_dir: Option<DataDir>,
    /// Why no source could be reached, when none could.
    pub failure: Option<String>,
}

impl std::fmt::Debug for Library {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("Library")
            .field("source", &self.source)
            .field("data_dir", &self.data_dir)
            .finish_non_exhaustive()
    }
}

impl Library {
    /// Probe the sources and connect to the best available one.
    ///
    /// Never fails. "No source available" is a state the interface must show
    /// anyway — a user without Zotero installed is not an error condition — so
    /// it is represented as [`ActiveSource::None`] rather than an `Err`.
    pub async fn connect(config: &Config, http: reqwest::Client) -> Self {
        let api = LocalApi::new(http);
        if api.is_running().await {
            return Self {
                source: ActiveSource::LocalApi,
                live: Some(api),
                offline: None,
                data_dir: None,
                failure: None,
            };
        }

        let resolved = datadir::resolve(config.data_dir.as_deref());
        let Some(dir) = resolved else {
            return Self::unavailable("no Zotero data directory could be located");
        };

        match SqliteSource::open(&dir.database(), &config.scratch) {
            Ok(source) => Self {
                source: ActiveSource::Sqlite,
                live: None,
                offline: Some(Mutex::new(source)),
                data_dir: Some(dir),
                failure: None,
            },
            Err(error) => {
                let mut library = Self::unavailable(&error.to_string());
                library.data_dir = Some(dir);
                library
            }
        }
    }

    fn unavailable(reason: &str) -> Self {
        Self {
            source: ActiveSource::None,
            live: None,
            offline: None,
            data_dir: None,
            failure: Some(reason.to_owned()),
        }
    }

    /// Which source is answering.
    pub fn source(&self) -> ActiveSource {
        self.source
    }

    /// Whether citation keys come from a source that owns them.
    ///
    /// `false` means keys are generated here and may not match what a
    /// collaborator's Better BibTeX produces. [ADR-0008] requires that this is
    /// flagged rather than assumed away.
    ///
    /// [ADR-0008]: https://github.com/GeneralPawz/yaz/blob/main/docs/adr/0008-zotero-integration.md
    pub fn keys_are_authoritative(&self) -> bool {
        matches!(self.source, ActiveSource::BetterBibTeX)
    }

    /// Search the library, or list recent items when the query is empty.
    pub async fn search(&self, query: &str, limit: usize) -> Result<Vec<Item>> {
        if let Some(api) = &self.live {
            return api.search(query, limit).await;
        }
        let Some(offline) = &self.offline else {
            return Err(Error::NotRunning);
        };
        // Scoped so the guard is dropped before returning, and so no `await`
        // can ever be introduced while it is held.
        let source = offline.lock().expect("zotero library mutex poisoned");
        if query.trim().is_empty() {
            source.recent(limit)
        } else {
            source.search(query, limit)
        }
    }

    /// Every marked passage on an item.
    pub async fn annotations(&self, item_key: &str) -> Result<Vec<Annotation>> {
        if let Some(api) = &self.live {
            return api.annotations(item_key).await;
        }
        let Some(offline) = &self.offline else {
            return Err(Error::NotRunning);
        };
        let source = offline.lock().expect("zotero library mutex poisoned");
        source.annotations(item_key)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn no_source_is_a_state_rather_than_an_error() {
        let library = Library::unavailable("nothing found");
        assert_eq!(library.source(), ActiveSource::None);
        assert!(!library.source().is_live());
        assert!(library.failure.is_some(), "the reason must be reportable");
    }

    #[test]
    fn only_better_bibtex_owns_citation_keys() {
        // The sqlite and local-API tiers make us generate keys, and the user has
        // to be told, because a generated key can disagree with a co-author's.
        for (source, authoritative) in [
            (ActiveSource::BetterBibTeX, true),
            (ActiveSource::LocalApi, false),
            (ActiveSource::Sqlite, false),
            (ActiveSource::ExportedBib, false),
            (ActiveSource::None, false),
        ] {
            let library = Library {
                source,
                live: None,
                offline: None,
                data_dir: None,
                failure: None,
            };
            assert_eq!(
                library.keys_are_authoritative(),
                authoritative,
                "{source:?}"
            );
        }
    }

    #[test]
    fn liveness_matches_the_adr_table() {
        assert!(ActiveSource::BetterBibTeX.is_live());
        assert!(ActiveSource::LocalApi.is_live());
        // An export is as current as the last export, which is not live.
        assert!(!ActiveSource::ExportedBib.is_live());
        assert!(!ActiveSource::Sqlite.is_live());
        assert!(!ActiveSource::None.is_live());
    }
}
