# en-US is the source of truth for message keys. Other locales are translations
# of this file; a key missing elsewhere falls back through the locale chain
# (de-AT → de → en-US) rather than rendering a raw key.
#
# ICU/Fluent so that plurals and gender work in the languages that need them —
# a naïve "{count} items" is wrong in Polish, Russian and Arabic.
#
# See docs/adr/0011-localisation.md

## Application

app-name = yaz
app-tagline = Turn your ideas and sources into papers.

## Filesystem errors — keys come from yaz-core::Error::message_key()

error-fs-not-found = Could not find { $path }.
error-fs-outside-root = { $path } is outside { $root }, which this operation is limited to.
error-fs-undecodable = Could not read { $path } as text. It may be a binary file or use an unsupported encoding.
error-fs-conflicting-write = { $path } was changed outside yaz since you opened it. Saving now would discard those changes.
error-fs-io = Something went wrong reading or writing { $path }.

## Compilation

compile-run = Compile
compile-running = Compiling…
compile-succeeded = Compiled in { $seconds }s.
compile-failed = Compilation failed.
compile-diagnostics-count = { $count } error(s)
compile-diagnostics =
    { $count ->
        [one] 1 problem
       *[other] { $count } problems
    }
compile-engine-unavailable = This project is set to use { $engine }, which is not installed. Install a TeX distribution, or switch this project to the built-in Tectonic engine.

## Engines

settings-engine = Engine
settings-engine-help = Saved in yaz.toml, so co-authors compile the same way you do.
engine-tectonic-not-built = Not included in this build of yaz. It has to be compiled in — a setting cannot add it.
engine-system-not-installed = Not installed on this computer.
engine-unavailable-suffix = unavailable

## Zotero — keys come from yaz-zotero::ActiveSource::status_key()

zotero-source-better-bibtex = Zotero: connected via Better BibTeX
zotero-source-local-api = Zotero: connected
zotero-source-exported-bib = Zotero: offline — reading an exported .bib
zotero-source-sqlite = Zotero: offline — reading the library database
zotero-source-none = Zotero: not available
zotero-keys-generated = Citation keys are generated by yaz because Better BibTeX is not available. They may not match a collaborator's.

## Plugin capabilities — generated reference reads these; keys come from
## yaz-plugin::Capability::description_key()

capability-fs-project-description = Read and change files in this project.
capability-fs-read-description = Read files at a specific location outside this project.
capability-fs-write-description = Change files at a specific location outside this project.
capability-net-description = Connect to the internet, limited to { $hosts }.
capability-process-description = Run programs on your computer: { $binaries }.
capability-zotero-description = Read your Zotero library.
capability-obsidian-description = Read your Obsidian vault.
capability-clipboard-description = Read and change the clipboard.
capability-notifications-description = Show desktop notifications.
capability-shell-open-description = Open links and files with your other applications.

## Plugin management

plugin-install-title = Install { $name }?
plugin-install-capabilities = This plugin is asking for:
plugin-install-unreviewed = This plugin has not been reviewed by anyone. Only install plugins from authors you trust.
plugin-update-new-capabilities = { $name } is asking for permissions it did not have before. Review them before updating.
plugin-error = { $name } stopped working.
plugin-error-disable = Disable { $name }

## Workspace

workspace-open-project = Open folder…
workspace-no-project = No folder open yet.
workspace-no-files = No .tex files in this folder.
workspace-no-file-open = Choose a file to start writing.
workspace-entry = entry

## Editor

editor-mode-source = Source
editor-mode-visual = Visual
editor-vim-mode = Vim
editor-loading = Opening…

## PDF

pdf-empty = Compile to see your document here.

## Settings

settings-appearance = Appearance
settings-theme = Theme
settings-colour-mode = Appearance mode
settings-colour-mode-system = Match system
settings-colour-mode-light = Light
settings-colour-mode-dark = Dark
settings-interface-locale = Interface language
settings-document-locale = Document language
settings-document-locale-help = The language you are writing in. Separate from the interface language — it sets spellchecking, hyphenation and quotation marks.
settings-check-for-updates = Check for updates
settings-check-for-updates-help = Contacts GitHub to see whether a newer version exists.

## Pickers

picker-placeholder = Type to filter
picker-empty = Nothing to show
picker-loading = Loading…
picker-failed = Could not load the list

## Plugin runtime

plugin-error-not-loaded = That plugin is not loaded.
capability-error-not-declared = The plugin did not ask for permission to do that.
capability-error-not-granted = You have not granted the plugin permission to do that.
capability-error-out-of-scope = That is outside what the plugin is allowed to reach.

## Zotero — commands

zotero-command-cite = Cite from Zotero
zotero-command-cite-description = Search your Zotero library and insert a citation.
zotero-command-quote = Quote a highlight
zotero-command-quote-description = Insert a passage you highlighted in Zotero, with its citation.
zotero-command-reconnect = Reconnect to Zotero
zotero-command-reconnect-description = Look again for a running Zotero, then fall back to the offline library.

## Zotero — pickers

zotero-picker-source-title = Choose a source
zotero-picker-source-placeholder = Search by title or author
zotero-picker-source-empty = Nothing in your library matches
zotero-picker-passage-title = Choose a passage you marked
zotero-picker-passage-placeholder = Filter the passages
zotero-picker-passage-empty = No passages match
zotero-page-label = p. { $page }

## Zotero — notices

zotero-notice-no-editor = Open a document first.
zotero-notice-unavailable = No Zotero library was found at { $detail }.
zotero-notice-no-annotations = You have not marked anything in that source.
zotero-notice-no-quotable-annotations = That source has marks, but none of them are quotable text.
zotero-notice-generated-key = Inserted { $key }. That key was generated by yaz and may not match a collaborator's.

## Zotero — annotation kinds

zotero-annotation-highlight = Highlight
zotero-annotation-note = Note
zotero-annotation-image = Image
zotero-annotation-ink = Drawing
zotero-annotation-underline = Underline
zotero-annotation-other = Other

## Zotero — where the library was found

zotero-datadir-configured = the folder you chose
zotero-datadir-profile = the folder your Zotero profile points at
zotero-datadir-convention = the default Zotero folder

## Zotero — errors

zotero-error-no-library = No Zotero library was found.
zotero-error-unsupported-schema = This Zotero library was made by a newer Zotero than yaz understands, so it was not read.
zotero-error-unsupported-journal = This Zotero library stores recent changes separately, and yaz would only have read an out-of-date copy.
zotero-error-not-running = Zotero is not running.
zotero-error-unexpected-response = Zotero answered in a way yaz did not understand.
zotero-error-http = Could not reach Zotero.
zotero-error-database = Your Zotero library could not be read.
zotero-error-io = A file could not be read or written.
zotero-error-item-not-found = That item is no longer in your Zotero library.

## Zotero — the live connection

zotero-live-available = Connected to Zotero
zotero-live-not-running = Zotero is not running
zotero-live-api-disabled = Zotero is running, but its local API is switched off
zotero-live-api-disabled-help = Turn on "Allow other applications on this computer to communicate with Zotero" in Zotero's Advanced settings to read the library live.
zotero-live-unexpected = Zotero answered unexpectedly
zotero-demoted = The live connection failed, so the library is being read from a copy on disk.

## Menu bar

menu-file = File
menu-edit = Edit
menu-view = View
menu-tools = Tools
menu-help = Help

menu-file-open-folder = Open folder…
menu-file-save = Save
menu-file-compile = Compile
menu-file-close-project = Close project
menu-edit-undo = Undo
menu-edit-redo = Redo
menu-edit-find = Find…
menu-view-vim = Vim keys
menu-view-connections = Connections
menu-tools-engine = Typesetting engine
menu-help-documentation = Documentation
menu-help-report-issue = Report an issue
menu-help-about = About yaz
menu-not-implemented = That is not built yet.

## Connections

connections-title = Connections
connections-none = Nothing is configured yet.
connections-reconnect = Reconnect
connections-zotero = Zotero
connections-obsidian = Obsidian
connections-not-configured = Not configured
connections-reading-offline = Reading a copy of the library on disk
connections-source = Source: { $source }

## Window controls

window-minimise = Minimise
window-maximise = Maximise
window-restore = Restore
window-close = Close

## Settings

settings-title = Settings
settings-section-general = General
settings-section-engine = Typesetting
settings-section-connections = Connections
settings-group-editor = Editor
settings-group-typesetting = Engine
settings-vim-help = Modal editing in both source and visual mode.
settings-engine-no-project = Open a project to choose its engine. The choice is saved per project.

## Connections, continued

connections-unknown = Not connected yet
connections-connect-zotero = Connect to Zotero
connections-reconnect-zotero = Reconnect to Zotero
menu-tools-connections = Connections
menu-edit-settings = Settings…

## Workspace

workspace-close-tab = Close tab
workspace-tab-editor = Source
workspace-tab-pdf = Preview
menu-view-tabs = Tabs
menu-view-reset-layout = Reset layout
