# en-US is the source of truth for message keys. Other locales are translations
# of this file; a key missing elsewhere falls back through the locale chain
# (de-AT → de → en-US) rather than rendering a raw key.
#
# ICU/Fluent so that plurals and gender work in the languages that need them —
# a naïve "{count} items" is wrong in Polish, Russian and Arabic.
#
# See docs/adr/0011-localisation.md

## Application

app-name = yaz
app-tagline = Turn your ideas and sources into papers.

## Filesystem errors — keys come from yaz-core::Error::message_key()

error-fs-not-found = Could not find { $path }.
error-fs-outside-root = { $path } is outside { $root }, which this operation is limited to.
error-fs-undecodable = Could not read { $path } as text. It may be a binary file or use an unsupported encoding.
error-fs-conflicting-write = { $path } was changed outside yaz since you opened it. Saving now would discard those changes.
error-fs-io = Something went wrong reading or writing { $path }.

## Compilation

compile-run = Compile
compile-running = Compiling…
compile-succeeded = Compiled in { $seconds }s.
compile-failed = Compilation failed.
compile-diagnostics-count = { $count } error(s)
compile-diagnostics =
    { $count ->
        [one] 1 problem
       *[other] { $count } problems
    }
compile-engine-unavailable = This project is set to use { $engine }, which is not installed. Install a TeX distribution, or switch this project to the built-in Tectonic engine.

## Engines

settings-engine = Engine
settings-engine-help = Saved in yaz.toml, so co-authors compile the same way you do.
engine-tectonic-not-built = Not included in this build of yaz. It has to be compiled in — a setting cannot add it.
engine-system-not-installed = Not installed on this computer.
engine-unavailable-suffix = unavailable

## Zotero — keys come from yaz-zotero::ActiveSource::status_key()

zotero-source-better-bibtex = Zotero: connected via Better BibTeX
zotero-source-local-api = Zotero: connected
zotero-source-exported-bib = Zotero: offline — reading an exported .bib
zotero-source-sqlite = Zotero: offline — reading the library database
zotero-source-none = Zotero: not available
zotero-keys-generated = Citation keys are generated by yaz because Better BibTeX is not available. They may not match a collaborator's.

## Plugin capabilities — generated reference reads these; keys come from
## yaz-plugin::Capability::description_key()

capability-fs-project-description = Read and change files in this project.
capability-fs-read-description = Read files at a specific location outside this project.
capability-fs-write-description = Change files at a specific location outside this project.
capability-net-description = Connect to the internet, limited to { $hosts }.
capability-process-description = Run programs on your computer: { $binaries }.
capability-zotero-description = Read your Zotero library.
capability-obsidian-description = Read your Obsidian vault.
capability-clipboard-description = Read and change the clipboard.
capability-notifications-description = Show desktop notifications.
capability-shell-open-description = Open links and files with your other applications.

## Plugin management

plugin-install-title = Install { $name }?
plugin-install-capabilities = This plugin is asking for:
plugin-install-unreviewed = This plugin has not been reviewed by anyone. Only install plugins from authors you trust.
plugin-update-new-capabilities = { $name } is asking for permissions it did not have before. Review them before updating.
plugin-error = { $name } stopped working.
plugin-error-disable = Disable { $name }

## Workspace

workspace-open-project = Open folder…
workspace-no-project = No folder open yet.
workspace-no-files = No .tex files in this folder.
workspace-no-file-open = Choose a file to start writing.
workspace-entry = entry

## Editor

editor-mode-source = Source
editor-mode-visual = Visual
editor-vim-mode = Vim
editor-loading = Opening…

## PDF

pdf-empty = Compile to see your document here.

## Settings

settings-appearance = Appearance
settings-theme = Theme
settings-colour-mode = Appearance mode
settings-colour-mode-system = Match system
settings-colour-mode-light = Light
settings-colour-mode-dark = Dark
settings-interface-locale = Interface language
settings-document-locale = Document language
settings-document-locale-help = The language you are writing in. Separate from the interface language — it sets spellchecking, hyphenation and quotation marks.
settings-check-for-updates = Check for updates
settings-check-for-updates-help = Contacts GitHub to see whether a newer version exists.
